/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package annuaire.view;

import annuaire.controleur.controleurPersonne;
import annuaire.dao.daoPersonne;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author anthony
 */
public class FrameCreerPersonne extends javax.swing.JFrame {
    daoPersonne daoP = new daoPersonne();

    public FrameCreerPersonne() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNumPersonne = new javax.swing.JLabel();
        lblNomPersonne = new javax.swing.JLabel();
        lblPrenomPersonne = new javax.swing.JLabel();
        lblEmailPersonne = new javax.swing.JLabel();
        lblDateNaissancePersonne = new javax.swing.JLabel();
        lblOrganisation = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaObservationPersonne = new javax.swing.JTextArea();
        txtNumeroPersonne = new javax.swing.JTextField();
        txtPrenomPersonne = new javax.swing.JTextField();
        txtNomPersonne = new javax.swing.JTextField();
        txtEmailPersonne = new javax.swing.JTextField();
        txtDateNaissancePersonne = new javax.swing.JTextField();
        txtOrganisation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreer.setBackground(new java.awt.Color(51, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Création d'une personne");

        lblNumPersonne.setText("Numéro * :");

        lblNomPersonne.setText("Nom :");

        lblPrenomPersonne.setText("Prénom :");

        lblEmailPersonne.setText("Em@il :");

        lblDateNaissancePersonne.setText("Date de naissance :");

        lblOrganisation.setText("Organisation :");

        jLabel8.setText("Observation :");

        jButton1.setText("Créer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        txtaObservationPersonne.setColumns(20);
        txtaObservationPersonne.setRows(5);
        jScrollPane1.setViewportView(txtaObservationPersonne);

        int idmax = this.daoP.getMaxIdP()+1;
        txtNumeroPersonne.setEditable(false);
        txtNumeroPersonne.setText(Integer.toString(idmax)
        );

        txtNomPersonne.setText(" ");

        txtEmailPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailPersonneActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("* attribué automatiquement");

        javax.swing.GroupLayout btnCreerLayout = new javax.swing.GroupLayout(btnCreer);
        btnCreer.setLayout(btnCreerLayout);
        btnCreerLayout.setHorizontalGroup(
            btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCreerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(btnCreerLayout.createSequentialGroup()
                .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnCreerLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1)
                        .addGap(208, 208, 208)
                        .addComponent(btnAnnuler))
                    .addGroup(btnCreerLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNomPersonne)
                            .addComponent(lblNumPersonne)
                            .addComponent(lblEmailPersonne)
                            .addComponent(lblDateNaissancePersonne)
                            .addComponent(lblOrganisation))
                        .addGap(18, 18, 18)
                        .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDateNaissancePersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEmailPersonne, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOrganisation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(btnCreerLayout.createSequentialGroup()
                                    .addComponent(txtNumeroPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2))
                                .addGroup(btnCreerLayout.createSequentialGroup()
                                    .addComponent(txtNomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(lblPrenomPersonne)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtPrenomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(btnCreerLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnCreerLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        btnCreerLayout.setVerticalGroup(
            btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCreerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPersonne)
                    .addComponent(txtNumeroPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomPersonne)
                    .addComponent(lblPrenomPersonne)
                    .addComponent(txtPrenomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailPersonne)
                    .addComponent(txtEmailPersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateNaissancePersonne)
                    .addComponent(txtDateNaissancePersonne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrganisation)
                    .addComponent(txtOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(btnCreerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnAnnuler))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCreer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCreer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void txtEmailPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailPersonneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailPersonneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        controleurPersonne pPersonne = new controleurPersonne();
        pPersonne.personneEnregistrement(this);
        JOptionPane.showMessageDialog(this, "La personne a été créée avec succès !", "Enregistrement effectué", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    public JButton getBtnAnnuler() {
        return btnAnnuler;
    }

    public void setBtnAnnuler(JButton btnAnnuler) {
        this.btnAnnuler = btnAnnuler;
    }

    public JPanel getBtnCreer() {
        return btnCreer;
    }

    public void setBtnCreer(JPanel btnCreer) {
        this.btnCreer = btnCreer;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblDateNaissancePersonne() {
        return lblDateNaissancePersonne;
    }

    public void setLblDateNaissancePersonne(JLabel lblDateNaissancePersonne) {
        this.lblDateNaissancePersonne = lblDateNaissancePersonne;
    }

    public JLabel getLblEmailPersonne() {
        return lblEmailPersonne;
    }

    public void setLblEmailPersonne(JLabel lblEmailPersonne) {
        this.lblEmailPersonne = lblEmailPersonne;
    }

    public JLabel getLblNomPersonne() {
        return lblNomPersonne;
    }

    public void setLblNomPersonne(JLabel lblNomPersonne) {
        this.lblNomPersonne = lblNomPersonne;
    }

    public JLabel getLblNumPersonne() {
        return lblNumPersonne;
    }

    public void setLblNumPersonne(JLabel lblNumPersonne) {
        this.lblNumPersonne = lblNumPersonne;
    }

    public JLabel getLblOrganisation() {
        return lblOrganisation;
    }

    public void setLblOrganisation(JLabel lblOrganisation) {
        this.lblOrganisation = lblOrganisation;
    }

    public JLabel getLblPrenomPersonne() {
        return lblPrenomPersonne;
    }

    public void setLblPrenomPersonne(JLabel lblPrenomPersonne) {
        this.lblPrenomPersonne = lblPrenomPersonne;
    }

    public JTextField getTxtDateNaissancePersonne() {
        return txtDateNaissancePersonne;
    }

    public void setTxtDateNaissancePersonne(JTextField txtDateNaissancePersonne) {
        this.txtDateNaissancePersonne = txtDateNaissancePersonne;
    }

    public JTextField getTxtEmailPersonne() {
        return txtEmailPersonne;
    }

    public void setTxtEmailPersonne(JTextField txtEmailPersonne) {
        this.txtEmailPersonne = txtEmailPersonne;
    }

    public JTextField getTxtNomPersonne() {
        return txtNomPersonne;
    }

    public void setTxtNomPersonne(JTextField txtNomPersonne) {
        this.txtNomPersonne = txtNomPersonne;
    }

    public JTextField getTxtNumeroPersonne() {
        return txtNumeroPersonne;
    }

    public void setTxtNumeroPersonne(JTextField txtNumeroPersonne) {
        this.txtNumeroPersonne = txtNumeroPersonne;
    }

    public JTextField getTxtOrganisation() {
        return txtOrganisation;
    }

    public void setTxtOrganisation(JTextField txtOrganisation) {
        this.txtOrganisation = txtOrganisation;
    }

    public JTextField getTxtPrenomPersonne() {
        return txtPrenomPersonne;
    }

    public void setTxtPrenomPersonne(JTextField txtPrenomPersonne) {
        this.txtPrenomPersonne = txtPrenomPersonne;
    }

    public JTextArea getTxtaObservationPersonne() {
        return txtaObservationPersonne;
    }

    public void setTxtaObservationPersonne(JTextArea txtaObservationPersonne) {
        this.txtaObservationPersonne = txtaObservationPersonne;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCreerPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCreerPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCreerPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCreerPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCreerPersonne().setVisible(true);
            }
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JPanel btnCreer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDateNaissancePersonne;
    private javax.swing.JLabel lblEmailPersonne;
    private javax.swing.JLabel lblNomPersonne;
    private javax.swing.JLabel lblNumPersonne;
    private javax.swing.JLabel lblOrganisation;
    private javax.swing.JLabel lblPrenomPersonne;
    private javax.swing.JTextField txtDateNaissancePersonne;
    private javax.swing.JTextField txtEmailPersonne;
    private javax.swing.JTextField txtNomPersonne;
    private javax.swing.JTextField txtNumeroPersonne;
    private javax.swing.JTextField txtOrganisation;
    private javax.swing.JTextField txtPrenomPersonne;
    private javax.swing.JTextArea txtaObservationPersonne;
    // End of variables declaration//GEN-END:variables
}
